from typing import Protocol


class Settings(Protocol):
	def get_login_docs_username(self) -> str: ...
	def get_login_docs_password(self) -> str: ...
	def get_database_url(self) -> str: ...
	def get_database_test_url(self) -> str: ...
